[package]
name = "left-right-candle"
version = "0.1.0"
description = "LEFT vs RIGHT: 12H Meme Candle Arena - Solana Program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "left_right_candle"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.30.1"

[profile.release]
overflow-checks = true

[dev-dependencies]
